### ISSUE TITLE
.scss files containing unicode characters may not compile nicely

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#958]
This is particularly apparent on the stock Vagrant box:

```
$ compass compile
    error sass/app.scss (Line 385 of sass/pages/_home.scss: Invalid US-ASCII character "\xE2")
    error sass/ie8.scss (Line 385 of sass/pages/_home.scss: Invalid US-ASCII character "\xE2")
Compilation failed in 2 files.
```

https://github.com/mysociety/theyworkforyou/blob/master/www/docs/style/sass/pages/_home.scss#L383 is the offending line in `_home.scss`, but this is also caused by #957.
